Fixed bugs
I2PC/xmippCore pull request #196
Opened 2023-12-01 10:12 UTC by MartinSalinas98

2023-12-01 12:06 UTC, MartinSalinas98 commented
@oierlauzi we have a [bug here](https://github.com/I2PC/xmippCore/blob/devel/core/utils/half.hpp#L3637) that we don't know how to solve (without possibly breaking functionality).

In summary, it's a uint_32 related to wither sine or cosine being negated, which might lead to integer overflow.
Since you added this file (8 months ago), you might know what is supposed to do better than us, and therefore know how to fix this.

Thanks!

2023-12-04 17:40 UTC, oierlauzi commented on core/alglib/ap.cpp
This is a external library. We should not change it on our own. In this case, use of `std::atomic` is incorrect, as `volatile` is not used for concurrency reasons (there is no concurrency in this code), but to prevent the compiler from optimizing out the last for loop

2023-12-04 17:53 UTC, oierlauzi commented on core/numerical_recipes.cpp
I don't see why this condition is never met

2023-12-04 17:57 UTC, oierlauzi requested changes
In general, I would not touch external libraries unless they contain a critical flaw. Otherwise, it is difficult to track changes when we want to upgrade those libraries.

2023-12-04 18:06 UTC, oierlauzi commented on core/alglib/ap.cpp
`std::atomic` implies `volatile` but it also implies certain cache invalidation procedures. Thus, any operation becomes several orders of magnitude slower. In this case, this behavior is not intended, as there is no concurrency. Additionally, as this function is used as a naive "wait", it may disturb timing assertions.

2023-12-04 18:09 UTC, MartinSalinas98 commented on core/numerical_recipes.cpp
It is not an unmet condition, it is a useless code. Ck = Ck does nothing, so that if is not needed

2023-12-04 18:11 UTC, oierlauzi commented on core/numerical_recipes.cpp
Okay, I did not focus on that part, jeje

2023-12-05 11:09 UTC, merged